version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend/models:/app/models
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "8080:80"        # Nginx serves React on port 80 inside container
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: humblehome
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  dbdata: