services:
  backend:
    build: ./backend
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend/models:/app/models
      - ./uploads:/app/uploads
      - ./var/log/humblehome:/app/var/log/humblehome
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  frontend:
    build: ./frontend
    ports:
    depends_on:
      - backend
    volumes:
      - ./frontend/certs:/etc/nginx/certs  # Mount SSL certificates

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: humblehome
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
      
volumes:
  dbdata:

