name: Test Docker Compose

on:
  push:
    branches:
      - main
jobs:
  test-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ensure log directory exists and has proper permissions
        run: |
          mkdir -p humblehome/var/log/humblehome
          chmod -R 777 humblehome/var/log/humblehome

      - name: Run Docker Compose
        run: |
          docker compose up --build -d
        working-directory: humblehome

      - name: Wait for docker to start up
        run: sleep 10

      - name: Wait for Service and Test Index Page
        run: |
          for i in {1..10}; do
            echo "Attempt $i: checking service..."
            if curl -s http://localhost/ -o response.html; then
              grep "<title>HumbleHome</title>" response.html
              echo "Service is up!"
              exit 0
            else
              echo "Waiting for service to start..."
              sleep 5
            fi
          done
          echo "Service did not start in time"
          docker compose logs
          exit 1
        working-directory: humblehome

      - name: Stop Docker Containers
        run: docker compose down
        working-directory: humblehome

  dependency-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NPM Dependencies
        run: npm install
        working-directory: humblehome/frontend

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "humblehome_main_branch"
          path: "humblehome"
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: dependency-check-report

  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.branch.name=main
